### ISSUE TITLE
Does it work in linux like ubuntu?

### ISSUE THREAD

**Issue by Macowe** [openstreams/wflow#1]
As the title, I just want to make it work in ubuntu, but there is a crack as below:
 model - ERROR - <type 'exceptions.AttributeError'>: 'WflowModel' object has no attribute 'sCatch'

**Comment by Macowe** [comment]
I think this is because that I changed the code  unconsciously, I download the latest release and my issue solved.

**Comment by jaapschellekens** [comment]
Great, good to hear it is resolved.
