### ISSUE TITLE
Kinematic wave iterations estimator results in pcrpow ** error

### ISSUE THREAD

**Issue by hcwinsemius** [openstreams/wflow#37]
In case the input variable Q in this function contains of a pcr grid with only zeros, this function will produce a pcrpow error. This only occurs in case wflow is called through bmi. Stand-alone the issue seems to be circumvented as the function apparently is only called after the first time step when Q already contains non-zero values. I propose to test the Q grid for unique zero values or test if its maximum lies above zero. That should solve the issue for this specific condition.

**Comment by visr** [comment]
Fixed by #38
