### ISSUE TITLE
wflow_emwaq fails writing fews output if runId contains directory

### ISSUE THREAD

**Issue by LBuckma** [openstreams/wflow#39]
@hboisgon 
If the runID contains a directory line 2305         comroot = os.sep.join([dwdir, "com", runId]) fails because it cannot create the directory and thus cannot create the file.

I suggest to remove the runID since you generally only couple one run (unless it is necessary for another reason). The resulting line would then read:
comroot = os.sep.join([dwdir, "com"])

The com files are then written to dwdir.

**Comment by rrea** [comment]
looks like a good issue to solve ...
