### ISSUE TITLE
some content missed in one script

### ISSUE THREAD

**Issue by pipipercy** [openstreams/wflow#49]
Hi,
i am trying to run the `wflow_prepare.ipynb` in path `./wflow/notebooks`,
however, i found something missed in `[12]`:
```python
tr.lddcreate("ldd.map",dem,True,
tr.report('ldd.map',ldd)
```
this makes confuse to me. Can you help me  complete this code?
Thanks for your kind support.

Best regards,
Percy

**Comment by pipipercy** [comment]
Thanks for your kind help.
I have reproduced these processes without much trouble.
One small issue may exist if `numpy` and `matplotlib.plot` is not imported for the `np` and `imshow`.

Glad to receive your note. However, in my work i want to couple some modules in `wflow` with machine learning. I am not familar with the modules about machine learning in `julia`. So i may stay in this version of `wflow` for a long time.

**Comment by verseve** [comment]
Ok, `%pylab` handles the import of `numpy` and `matplotlib`, so no issue there.
Indeed, you could set `Verbose` from the notebook.
