### ISSUE TITLE
Routing needs to be stripped from wflow_sbm and wflow_hbv

### ISSUE THREAD

**Issue by jaapschellekens** [openstreams/wflow#5]
Routing needs to be stripped from wflow_sbm and wflow_hbv

1.  Strip routing
2. Make combined scripts to replace old functionality

Questions: what about surfacewater soil interaction in sbm>

**Comment by verseve** [comment]
This has been done in [Wflow.jl](https://github.com/Deltares/Wflow.jl), lateral concepts as routing are now independent of vertical concepts like SBM and HBV.
