### ISSUE TITLE
is there a way to specify natural depression/reservoir in an area for simulation?

### ISSUE THREAD

**Issue by arsalansaghir1** [openstreams/wflow#53]
I have been wondering if there is a way to specify natural depressions/storage areas in wflow?
Like for example, flow stream comes in the depression and water is stored there

**Comment by verseve** [comment]
For river flow you could use the reservoir or lake functionality to mimic depression /storage areas. For overland flow, this is not possible. For both river and overland flow the kinematic wave approach is used, and as part of the kinematic wave it is not possible to define a (natural) depression storage. 

It would be helpful if you could explain in a bit more detail your specific use case. For example, for what type of catchment do you need this functionality, what is the model resolution, and what is your objective (e.g. to improve simulation results, studying measures to reduce flood peaks etc.)?

Also note that there will be no further developments in this wflow Python version. Developments have continued in the wflow Julia version, see also https://github.com/Deltares/Wflow.jl. Wflow.jl also includes the local inertial model (https://deltares.github.io/Wflow.jl/dev/model_docs/lateral/local-inertial/), which could be more suitable for your model case.

**Comment by arsalansaghir1** [comment]
Could you kindly tell me in detail how to mimic using the reservoir or lake functionality?

**Comment by verseve** [comment]
> Could you kindly tell me in detail how to mimic using the reservoir or lake functionality?

https://wflow.readthedocs.io/en/latest/wflow_funcs.html#reservoirs-and-lakes
